# Generated by Django 3.1 on 2021-01-03 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('price', models.FloatField()),
                ('contact_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('photos_or_videos', models.FileField(upload_to='user_service/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User listed service as provider', on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_provider',
                'ordering': ['-added_at'],
            },
        ),
    ]
