# Generated by Django 3.1 on 2021-02-27 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_picture", models.ImageField(upload_to="user/profile")),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField()),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("citizenship", "Citizenship"),
                            ("driving-license", "Driving License"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identification_number", models.CharField(max_length=20)),
                (
                    "identification_file",
                    models.FileField(upload_to="agent/identification"),
                ),
                ("accept_terms_and_condition", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_detail",
                "ordering": ["-added_at"],
            },
        ),
    ]
