# Generated by Django 3.1 on 2021-04-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210413_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_otp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='UserOtp',
        ),
    ]
