# Generated by Django 3.1 on 2021-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20210513_0725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdetail",
            name="designation",
            field=models.CharField(
                choices=[("F", "Field Manager"), ("E", "Engineer"), ("C", "Cameraman")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="state",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=60,
                null=True,
            ),
        ),
    ]
