# Generated by Django 3.1 on 2021-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_agentdetail_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdetail",
            name="terms_and_conditions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="terms_and_conditions",
            field=models.BooleanField(default=False),
        ),
    ]
