# Generated by Django 3.1 on 2021-07-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20210707_1134"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentdetail",
            name="accept_terms_and_condition",
        ),
    ]
