# Generated by Django 3.1 on 2021-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210517_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffdetail',
            name='state',
            field=models.CharField(choices=[('P', 'Pokhara'), ('K', 'Kathmandu'), ('L', 'Lalitpur')], max_length=60, null=True),
        ),
    ]
