# Generated by Django 3.1 on 2021-05-30 07:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210526_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
    ]
