# Generated by Django 3.1 on 2021-07-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_auto_20210721_0518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(),
        ),
    ]
