# Generated by Django 3.1 on 2021-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="facing_direction",
            field=models.CharField(
                choices=[
                    ("E", "EAST"),
                    ("W", "WEST"),
                    ("N", "North"),
                    ("S", "South"),
                    ("NE", "North-East"),
                    ("SE", "South-East"),
                    ("NW", "North-West"),
                    ("SW", "South-West"),
                    ("D", "Don't Know"),
                ],
                default="E",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="floor_number",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="total_floors",
            field=models.CharField(max_length=40),
        ),
    ]
