# Generated by Django 3.1 on 2021-04-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='propertydiscussionboard',
            options={'verbose_name': 'Property Discussion Board'},
        ),
        migrations.AlterModelOptions(
            name='propertyinfo',
            options={'ordering': ['-created_on'], 'verbose_name': 'Property Info'},
        ),
        migrations.AlterModelOptions(
            name='rentalinfo',
            options={'ordering': ['-created_on'], 'verbose_name': 'Rental Info'},
        ),
    ]
