# Generated by Django 3.1 on 2021-07-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellpropertydetails",
            name="total_floors",
            field=models.CharField(max_length=50),
        ),
    ]
