# Generated by Django 3.1 on 2021-07-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_details",
                to="property.city",
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="property_categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_details",
                to="property.propertycategories",
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="property_types",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_details",
                to="property.propertytypes",
            ),
        ),
    ]
