# Generated by Django 3.1 on 2021-05-07 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='property_type',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], default='R', max_length=1),
        ),
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('B', 'Buy'), ('R', 'Rent'), ('S', 'Sell')], max_length=1)),
                ('property_type', models.CharField(choices=[('B', 'House/Bungalow'), ('F', 'Flat & Apartment'), ('C', 'Commercial Property'), ('L', 'land'), ('A', 'Agricultural Land'), ('O', 'Office Space'), ('S', 'Shutter & Shop Space'), ('R', 'Restaurant for sale'), ('H', 'House in a Colony')], max_length=1)),
                ('urgent', models.CharField(choices=[('V', 'Very Urgent'), ('W', 'Within a few days'), ('M', 'Within a month'), ('I', 'In few months time')], max_length=1)),
                ('place', models.TextField()),
                ('price_range', models.TextField()),
                ('size', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_propertyrequest_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name_plural': 'Property Request',
                'db_table': 'property_request',
            },
        ),
    ]
