# Generated by Django 3.1 on 2021-04-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('cleaned', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('available_days', models.CharField(blank=True, choices=[('E', 'Everyday(Sunday - Saturday)'), ('W', 'Weekdays(Sunday - Friday)'), ('S', 'Weekend(Saturday)')], default='E', max_length=1, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_schedule', to='property.propertyinfo')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
                'db_table': 'property_schedule',
            },
        ),
    ]
