# Generated by Django 3.1 on 2021-07-07 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyrequest",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
