# Generated by Django 3.1 on 2021-03-24 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='locality',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='property',
            name='residential',
            field=models.CharField(blank=True, choices=[('R', 'Rent'), ('S', 'Resale'), ('P', 'Pg/Hostel'), ('F', 'Flatmates')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('B', 'Buy'), ('R', 'Rent'), ('S', 'Sell')], max_length=1)),
                ('property_type', models.CharField(choices=[('B', 'House/Bungalow'), ('F', 'Flat & Apartment'), ('C', 'Commercial Property'), ('L', 'Land'), ('A', 'Agricultural Land'), ('O', 'Office Space'), ('S', 'Shutter & Shop Space'), ('R', 'Restaurant for Sale'), ('H', 'House in a Colony')], max_length=1)),
                ('urgent', models.CharField(choices=[('V', 'Very Urgent'), ('D', 'Within a few days'), ('M', 'Within a month'), ('F', 'in few months time')], max_length=1)),
                ('property_address', models.CharField(max_length=63)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parking_space', models.FloatField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('size', models.FloatField()),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_propertyrequest_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'db_table': 'property_request',
                'ordering': ['name'],
            },
        ),
    ]
