# Generated by Django 3.1 on 2021-04-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='city',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
