# Generated by Django 3.1 on 2020-12-30 11:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDiscussionBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.CharField(choices=[('Q', 'Query'), ('R', 'Review'), ('S', 'Suggestion'), ('C', 'Complaint')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, size=None)),
                ('comments', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='property.property')),
            ],
            options={
                'db_table': 'property_property_discussion',
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='property.property')),
            ],
            options={
                'db_table': 'property_field_visit',
                'ordering': ['name'],
            },
        ),
    ]
