# Generated by Django 3.1 on 2021-04-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210401_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='fieldvisit',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Field Visit'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='propertydiscussionboard',
            options={'verbose_name_plural': 'Property Discussion Board'},
        ),
        migrations.AlterModelOptions(
            name='propertyinfo',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Property Info'},
        ),
        migrations.AlterModelOptions(
            name='rentalinfo',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Rental Info'},
        ),
    ]
