# Generated by Django 3.1 on 2021-07-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_auto_20210706_0726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="property_age",
            field=models.CharField(max_length=40),
        ),
    ]
