# Generated by Django 3.1 on 2021-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210507_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
