# Generated by Django 3.1 on 2021-05-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0002_floorplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydiscussionboard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discussion_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
