# Generated by Django 3.1 on 2021-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_auto_20210707_0733"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyrequest",
            name="description_assigned_to_employee",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertyrequest",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
