# Generated by Django 3.1 on 2021-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_auto_20210711_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyrequest",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
