# Generated by Django 3.1 on 2021-01-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210101_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='society_amenities',
            field=models.ManyToManyField(related_name='amenities', to='property.SocietyAmenities'),
        ),
    ]
