# Generated by Django 3.1 on 2021-05-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210513_0725'),
        ('property', '0003_auto_20210507_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='user.adminprofile'),
        ),
    ]
