# Generated by Django 3.1 on 2021-07-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_auto_20210706_0730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="city_locations",
                to="property.city",
            ),
            preserve_default=False,
        ),
    ]
