# Generated by Django 3.1 on 2021-07-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_auto_20210708_0730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenities",
            name="basic_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenities",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fieldvisit",
            name="basic_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_visit",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="localitydetails",
            name="basic_details",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentaldetails",
            name="basic_details",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_details",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentgallery",
            name="basic_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="basic_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rent_property",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resaledetails",
            name="basic_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resale_details",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sellpropertydetails",
            name="basic_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sell_property_details",
                to="property.basicdetails",
            ),
            preserve_default=False,
        ),
    ]
