# Generated by Django 3.1 on 2021-01-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210101_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('T', 'Top'), ('P', 'Premium'), ('F', 'Featured')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
