# Generated by Django 3.1 on 2021-07-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_auto_20210707_0800"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locality",
            options={"ordering": ["-created_on"]},
        ),
    ]
