# Generated by Django 3.1 on 2021-05-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210419_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
