# Generated by Django 3.1 on 2021-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_auto_20210706_0749"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicdetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basicdetails",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
