# Generated by Django 3.1 on 2021-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyinfo_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='status',
            field=models.CharField(choices=[('N', 'Negotation'), ('P', 'Pending')], max_length=2, null=True),
        ),
    ]
