# Generated by Django 3.1 on 2021-07-08 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0004_auto_20210708_0823"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last modified at"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(upload_to="property/gallery")),
                (
                    "basic_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="property.basicdetails",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_gallery_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Gallery",
                "db_table": "Gallery",
            },
        ),
        migrations.RemoveField(
            model_name="amenities",
            name="image",
        ),
        migrations.RemoveField(
            model_name="amenities",
            name="title",
        ),
        migrations.DeleteModel(
            name="RentGallery",
        ),
    ]
