# Generated by Django 3.1 on 2021-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_auto_20210708_0904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property/gallery"
            ),
        ),
    ]
