# Generated by Django 3.1 on 2021-07-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_auto_20210706_0941"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resaledetails",
            options={
                "ordering": ["-created_on"],
                "verbose_name_plural": "ResaleDetails",
            },
        ),
        migrations.AlterModelTable(
            name="basicdetails",
            table=None,
        ),
    ]
