# Generated by Django 3.1 on 2021-06-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_auto_20210604_0933"),
        ("property", "0005_auto_20210606_0539"),
    ]

    operations = []
