# Generated by Django 3.1 on 2021-05-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='listing',
            field=models.CharField(default='', max_length=20),
        ),
    ]
