# Generated by Django 3.1 on 2021-07-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_auto_20210708_0906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(default=1, upload_to="property/gallery"),
            preserve_default=False,
        ),
    ]
