# Generated by Django 3.1 on 2021-05-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_location_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='status',
            field=models.CharField(choices=[('N', 'negotiation'), ('P', 'Pending')], max_length=2, null=True),
        ),
    ]
