# Generated by Django 3.1 on 2021-06-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_auto_20210606_0646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="property.comment",
            ),
        ),
    ]
