# Generated by Django 3.1 on 2021-07-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0007_floorplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenities",
            old_name="lift",
            new_name="backup_electricity",
        ),
        migrations.RemoveField(
            model_name="basicdetails",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="basicdetails",
            name="owner",
        ),
        migrations.AddField(
            model_name="amenities",
            name="car_parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="cctv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="earthquake_resistant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="fire_safety",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="gated_community",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="hot_water",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="maintenance_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="play_area",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenities",
            name="water_purifier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="basicdetails",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_detail_postedby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentpropertydetails",
            name="property_size_choice",
            field=models.CharField(
                choices=[("R", "Ropani"), ("A", "Aana"), ("S", "Square Feet")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellpropertydetails",
            name="property_size_choice",
            field=models.CharField(
                choices=[("R", "Ropani"), ("A", "Aana"), ("S", "Square Feet")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="amenities",
            name="basic_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenities",
                to="property.basicdetails",
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_detail_agent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_detail_staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="property_age",
            field=models.CharField(
                choices=[
                    ("U", "Under Construction"),
                    ("L", "Less than a year"),
                    ("1", "1 to 3 year"),
                    ("3", "3 to 5 year"),
                    ("5", "5 to 10 year"),
                    ("M", "More than 10 year"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="property_size",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sellpropertydetails",
            name="property_age",
            field=models.CharField(
                choices=[
                    ("U", "Under Construction"),
                    ("L", "Less than a year"),
                    ("1", "1 to 3 year"),
                    ("3", "3 to 5 year"),
                    ("5", "5 to 10 year"),
                    ("M", "More than 10 year"),
                ],
                max_length=2,
            ),
        ),
    ]
