# Generated by Django 3.1 on 2021-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_auto_20210718_0616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="property_size_choice",
            field=models.CharField(
                choices=[("R", "Ropani"), ("A", "Aana"), ("S", "Square Feet")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="sellpropertydetails",
            name="property_size_choice",
            field=models.CharField(
                choices=[("R", "Ropani"), ("A", "Aana"), ("S", "Square Feet")],
                max_length=1,
            ),
        ),
    ]
