# Generated by Django 3.1 on 2021-07-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_auto_20210718_0621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentpropertydetails",
            name="property_size_choice",
            field=models.CharField(
                choices=[
                    ("Sf", "Sq Feet"),
                    ("sm", "Sq Meter"),
                    ("A", "Aana"),
                    ("R", "Ropani"),
                    ("K", "Kattha"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="sellpropertydetails",
            name="property_size_choice",
            field=models.CharField(
                choices=[
                    ("Sf", "Sq Feet"),
                    ("sm", "Sq Meter"),
                    ("A", "Aana"),
                    ("R", "Ropani"),
                    ("K", "Kattha"),
                ],
                max_length=2,
            ),
        ),
    ]
