# Generated by Django 3.1 on 2021-07-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_auto_20210718_0627"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenities",
            name="lift",
            field=models.BooleanField(default=False),
        ),
    ]
