# Generated by Django 3.1 on 2021-06-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0011_auto_20210624_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyinfo",
            name="condition_type",
            field=models.CharField(
                blank=True,
                choices=[("N", "New"), ("U", "Used")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyinfo",
            name="listing_type",
            field=models.CharField(
                blank=True,
                choices=[("T", "Top"), ("P", "Premium"), ("F", "Featured")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyinfo",
            name="membership_plan",
            field=models.CharField(
                blank=True,
                choices=[("S", "Silver"), ("G", "Gold"), ("P", "Platinum")],
                max_length=1,
                null=True,
            ),
        ),
    ]
