# Generated by Django 3.1 on 2021-07-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_auto_20210719_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locality",
                to="property.city",
            ),
        ),
    ]
