# Generated by Django 3.1 on 2021-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_auto_20210627_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyinfo",
            name="property_size",
            field=models.FloatField(default=0.0),
        ),
    ]
