# Generated by Django 3.1 on 2021-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0014_locality_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locality",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
