# Generated by Django 3.1 on 2021-07-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0015_auto_20210720_0817"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenities",
            name="hot_water",
        ),
    ]
